# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  The natural logarithm of the sum of the exponentials of the arguments
#'
#' A numerically stable version of \code{log(sum(exp(x)))}
#' @param x a numeric vector
#'
#' @return The natural logarithm of sum of \code{exp(x)}
#' @export
#' @examples
#' x=c(-1000,-1001)
#' log(sum(exp(x))) ##naive implementation
#' log_sum_exp(x) ##numerically stable implementation
log_sum_exp <- function(x) {
    .Call(`_CAPPMx_log_sum_exp`, x)
}

sanity <- function(x) {
    invisible(.Call(`_CAPPMx_sanity`, x))
}

mixture_cat <- function(alpha, nmix, ncat, nrun, burn, thin, eta1, eta2, non_na_obs1, del1, del2) {
    .Call(`_CAPPMx_mixture_cat`, alpha, nmix, ncat, nrun, burn, thin, eta1, eta2, non_na_obs1, del1, del2)
}

common_atoms_cat <- function(alpha, nmix, ncat, aa, ba, al, bl, nrun, burn, thin, eta1, eta2, st1, nu1, st2, nu2, non_na_obs1, del1, del2, tau) {
    .Call(`_CAPPMx_common_atoms_cat`, alpha, nmix, ncat, aa, ba, al, bl, nrun, burn, thin, eta1, eta2, st1, nu1, st2, nu2, non_na_obs1, del1, del2, tau)
}

common_atoms_cat_lognormal <- function(nmix, ncat, a0, df0, mu_m, mu_v, b_m, b_v, nrun, burn, thin, eta1, eta2, eta_cont1, eta_cont2, st1, nu1, st2, nu2, non_na_obs1, non_na_obs1_cont, del1, del2, del_range_lognorm, nleapfrog_lognorm, alpha_hyper, del_range_alp1, nleapfrog_alp1, del_range_alp2, nleapfrog_alp2) {
    .Call(`_CAPPMx_common_atoms_cat_lognormal`, nmix, ncat, a0, df0, mu_m, mu_v, b_m, b_v, nrun, burn, thin, eta1, eta2, eta_cont1, eta_cont2, st1, nu1, st2, nu2, non_na_obs1, non_na_obs1_cont, del1, del2, del_range_lognorm, nleapfrog_lognorm, alpha_hyper, del_range_alp1, nleapfrog_alp1, del_range_alp2, nleapfrog_alp2)
}

